const sb = window.supabase.createClient(
  'https://buyjbhoyslfdbpmvrvkp.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1eWpiaG95c2xmZGJwbXZydmtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzNTM5MzAsImV4cCI6MjA5MTkyOTkzMH0.92qNTJPdsQEE1SLvAiZ_bly9dy0MpXqzQZ8qNMrwhUY'
);